# Copyright (c) 2025 Ferrous Systems
# SPDX-License-Identifier: CC0-1.0

[build]
target = ["thumbv7em-none-eabi"]

[target.thumbv7em-none-eabi]
rustflags = [
    "-Clink-arg=-Tlink.x",
    "-Clink-arg=-Tdefmt.x",
]
runner = "./qemu_run.sh"

[env]
DEFMT_LOG="debug"
