name: test
on: [push, pull_request, merge_group]
jobs:
  test-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [thumbv6m-none-eabi, thumbv7m-none-eabi, thumbv7em-none-eabi, thumbv7em-none-eabihf, thumbv8m.base-none-eabi, thumbv8m.main-none-eabi, thumbv8m.main-none-eabihf]
    steps:
      - uses: actions/checkout@v4
      - name: Install Target
        run: |
          rustup target add ${{ matrix.target }}
      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libpixman-1-0 libfdt1 libglib2.0-0t64
      - name: Install QEMU
        run: |
          curl -sSL https://github.com/jonathanpallant/qemu9-for-ubuntu-2404/releases/download/qemu-9.2.3%2Bbuild0/qemu-9.2.3-ubuntu-24.04.tar.gz | sudo tar xvzf - -C /
      - name: Install defmt-print
        uses: baptiste0928/cargo-install@v3
        with:
          crate: defmt-print
      - name: Run example and check outputs
        run: |
          export PATH=/opt/qemu/bin:$PATH
          cd examples
          cargo run --target=${{ matrix.target }} --release --bin ci-check | tee ci-check-${{ matrix.target }}.txt
          diff ci-check-${{ matrix.target }}.txt ./reference/ci-check-${{ matrix.target }}.txt
  test-all:
    runs-on: ubuntu-latest
    needs: [test-examples]
    steps:
      - run: /bin/true
